clip:
  symbol: clip
  args: {}

clip_text_context_encoder:
  super_cfg: clip
  type: clip_text_context_encoder
  args: {}

clip_image_context_encoder:
  super_cfg: clip
  type: clip_image_context_encoder
  args: {}
