vd_base:
  symbol: vd
  find_unused_parameters: true
  type: vd_v2_0
  args:
    beta_linear_start: 0.00085
    beta_linear_end: 0.012
    timesteps: 1000
    use_ema: false

###########
# vd v1.0 #
###########

vd_four_flow_v1-0:
  super_cfg: vd_base
  args:
    vae_cfg_list:
      - [image, MODEL(autokl_v1)]
      - [text, MODEL(optimus_v1)]
    ctx_cfg_list:
      - [image, MODEL(clip_image_context_encoder)]
      - [text, MODEL(clip_text_context_encoder)]
    diffuser_cfg_list:
      - [image, MODEL(openai_unet_2d_v1)]
      - [text, MODEL(openai_unet_0d_v1_dc)]
    global_layer_ptr: image
    latent_scale_factor: 
      image: 0.18215
